print('Digite três números, que serão somados pelos quadrados dos mesmos')
n1 = float(input('Número 1: '))
n2 = float(input('Número 2: '))
n3 = float(input('Número 3: '))
soma = (n1 ** 2) + (n2 ** 2) + (n3 ** 3)
print(f'o valor da soma dos números ao quadrados é: {soma}')