print('Digite três valores, que serão somados pelos quadrados dos mesmos')
n1 = float(input())
n2 = float(input())
n3 = float(input())
soma = (n1 ** 2) + (n2 ** 2) + (n3 ** 3)
print(f'o valor da soma dos números ao quadrados é: {soma}')