print('Digite um número de 4 digitos (1000 a 9999')
num = int(input())
print(f'O primeiro dígito é : {str(num) [0]}')
print(f'O segundo dígito é : {str(num) [1]}')
print(f'O terceiro dígito é : {str(num) [2]}')
print(f'O quarto dígito é : {str(num) [3]}')